### ISSUE TITLE
问一下作者，这个库对比Fragmentation，有哪些改进吗？

### ISSUE THREAD

**Issue by Jason-Lee-1001** [weikaiyun/EasyFragmentation#3]
如题，看了接口跟 Fragmentation 是一样的，想知道对比来讲改进了哪些部分，毕竟那个已经不维护了，而 JetPack Navigation 不怎么灵活

**Comment by weikaiyun** [comment]
> 如题，看了接口跟 Fragmentation 是一样的，想知道对比来讲改进了哪些部分，毕竟那个已经不维护了，而 JetPack Navigation 不怎么灵活

可见性判断，懒加载，转场动画都进行了改写。 现在的可见性和懒加载是利用fragmentmanager的setMaxlifecycle进行实现的，然后转场动画就是fragment的转场动画，无需模拟，原库进行popTo动画是需要进行模拟的。现在代码逻辑更加简洁，清晰。欢迎适用，同时可以clone源代码查阅，我认为是完全可以看懂源代码的。

**Comment by weikaiyun** [comment]
另外还有一点就是 少了很多trick, 源码上我觉得更自然，基本都是利用的原生的能力。另外现在支持viewpager和viewpager2  其实原库是不支持viewpager2的。

**Comment by weikaiyun** [comment]
Navigation个人觉得确实不够灵活，这也是我想改造fragmentation的原因所在。

**Comment by Jason-Lee-1001** [comment]
谢谢，原库确实渐渐出现一些问题，当然不是这个库的原因，而是原生API的废弃所导致，抽时间也试一下作者这个
